---
- name: Tap Homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/binary
    - homebrew/completions
    - homebrew/dupes
    - phinze/cask
    - mdodsworth/local

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup
  register: brew_result
  changed_when: "brew_result.stdout != 'Already up-to-date.'"

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - ant
    - apache-spark
    - awscli
    - bash
    - bash-completion
    - brew-cask
    - docker
    - gist
    - git
    - go
    - gradle
    - hbase
    - leiningen
    - mariadb
    - maven
    - node
    - packer
    - postgresql
    - protobuf
    - ruby
    - scala
    - tree
    - vagrant-completion
    - vim
    - wget

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

- name: Install applications with Homebrew-cask
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - adium
    - alfred
    - colloquy
    - dash
    - dropbox
    - evernote
    - intellij-idea
    - intellij-idea-eap
    - java
    - macvim
    - spotify
    - vagrant
    - virtualbox

- name: Install NPM packages
  npm: name={{ item }} state=latest global=yes
  with_items:
    - coffee-script
    - yo

- name: Install gem packages
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - compass
