---
- name: add the version of bash installed by homebrew
  lineinfile: dest=/etc/shells regexp=^/usr/local/bin/bash line=/usr/local/bin/bash
  sudo: yes

- name: switch the version of bash installed by homebrew
  shell: chsh -s /usr/local/bin/bash {{ username }}
  sudo: yes
