- hosts: all
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/packages.yml
    - include: tasks/intellij.yml
    - include: tasks/vim.yml
    - include: tasks/shell.yml
      vars:
        username: mdodsworth
